version: '3'

services:
 app:
  build:
   context: .
   args:
    - VERSION=3.7.0-alpine3.8
  image: thomas/students-service:0.1
  environment:
    - FLAST_ENV=development
  ports:
   - 8080:5000
  depends_on:
   - redis
  networks:
   - mynet
 redis:
  image: redis:4.0.11-alpine
  networks:
   - mynet
  volumes:
   - mydata:/data

networks:
 mynet:
volumes:
 mydata:

